server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: ms-estoque
  datasource:
    url: jdbc:postgresql://localhost:5432/estoqueDB
    username: postgres
    password: root
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      estoque-historico: topic_estoque_historico

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
springdoc:
  api-docs:
    path: /api-docs
    version: openapi_3_0
  swagger-ui:
    path: /swagger-ui.html
    csrf:
      enabled: false
  show-actuator: true
  default-produces-media-type: "application/json"